/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 26
#define YY_END_OF_BUFFER 27
static yyconst short int yy_accept[318] =
    {   0,
        0,    0,    0,    0,   27,   25,   24,   24,   10,    2,
       25,   25,   19,    2,    2,   18,   18,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   18,   18,   18,
       18,   18,   18,    2,    4,   16,   17,   16,   10,    9,
        0,   23,   14,    1,   22,   19,   21,   21,    0,    0,
       10,   18,   18,   18,   18,   18,   18,   18,   18,   18,
       18,   12,   18,   18,   18,   18,   18,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   18,    2,    4,
       15,    0,    1,   22,    0,    0,   20,    3,   18,   18,

       18,   18,   18,   18,   18,   18,   18,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   18,   18,    0,
       23,    0,    0,   22,   11,   18,   18,   18,   12,   18,
       18,   18,   18,   18,   18,   18,   18,   18,    2,   18,
       18,   18,   18,   18,   13,   18,   18,    2,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   18,   18,   18,
       18,   18,    0,   22,   18,   18,   18,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   18,    2,   18,   18,

       18,   18,   18,   18,   18,   18,   18,   18,   18,   18,
       18,   18,   18,   18,   18,    2,   18,   18,    2,   18,
       18,   18,   18,   18,   18,   18,   18,   18,   18,   18,
       18,   18,    0,   18,   18,   18,   18,   18,   18,   18,
       18,   18,   18,   18,   18,   18,    0,    0,    0,    8,
        0,   18,   18,   18,   18,   18,   18,   18,   18,   18,
       18,   18,    0,    0,    6,    0,    0,    0,    0,    8,
        0,   18,   18,   18,   18,   18,   18,   18,    0,    0,
        0,    6,    0,    0,    0,    7,    0,   18,   18,    3,
       18,   18,    0,    0,    5,    0,    7,    0,    0,    0,

       18,   18,   18,    5,    0,    0,    0,   18,   18,   18,
       18,   18,   18,   18,   18,   18,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    4,    5,    1,    1,    6,    1,    7,
        8,    9,   10,   11,   10,   12,   13,   14,   14,   14,
       14,   14,   14,   14,   14,   14,   14,    1,    1,   15,
       16,   17,    1,    1,   18,   18,   18,   18,   19,   18,
       18,   18,   18,   18,   18,   18,   18,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   18,   18,   18,
        1,   20,    1,   21,    1,    1,   22,   23,   24,   25,

       26,   27,   28,   29,   30,   31,   32,   33,   34,   35,
       36,   37,   38,   39,   40,   41,   42,   43,   44,   45,
       46,   47,    1,   48,    1,   49,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[50] =
    {   0,
        1,    1,    2,    3,    1,    1,    1,    4,    1,    1,
        4,    5,    1,    6,    1,    1,    1,    6,    6,    1,
        1,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    1,    1
    } ;

static yyconst short int yy_base[334] =
    {   0,
        0,  748,   47,   48,  748,  847,  847,  847,   48,  847,
      732,   45,   41,  730,  727,  739,   55,   57,   58,   62,
       59,   66,   65,   60,   67,   61,   77,   81,   68,   82,
      104,   74,  111,  694,    0,  847,  847,  727,   69,  847,
      736,  102,  847,    0,  108,  117,   62,  125,  721,  720,
      120,  731,  126,  121,  114,  128,  134,  137,  140,  138,
      141,  143,  147,  148,  145,  151,  152,  153,  154,  156,
      158,  160,  159,  157,  166,  162,  163,   71,  167,  172,
      185,  175,  178,  187,  179,  176,  204,  177,  847,    0,
      847,  202,    0,  196,  207,  719,  718,  847,  214,  215,

      216,  219,  223,  220,  224,  225,  226,  228,  227,  232,
      231,  229,  236,  234,  235,  237,  238,  239,  241,  257,
      258,  244,  259,  264,  265,  268,  269,  270,  274,  271,
      276,  281,  278,  280,  282,  286,  284,  283,  285,  717,
      716,  282,  715,  714,  723,  290,  293,  291,  722,  294,
      295,  297,  301,  298,  304,  310,  313,  314,  320,  324,
      325,  328,  329,  331,  721,  333,  334,  336,  337,  340,
      341,  345,  343,  349,  344,  346,  350,  347,  352,  353,
      357,  358,  708,  707,  361,  359,  375,  360,  378,  379,
      383,  385,  386,  387,  388,  391,  393,  392,  396,  397,

      399,  398,  402,  403,  404,  407,  405,  165,  414,  408,
      406,  411,  412,  420,  416,  664,  413,  423,  425,  436,
      437,  439,  441,  445,  451,  452,  446,  449,  453,  455,
      454,  458,  495,  461,  464,  465,  541,  542,  456,  463,
      544,  543,  466,  462,  545,  546,  585,  651,  548,  645,
      470,  468,  549,  631,  551,  554,  550,  632,  633,  634,
      635,  638,  567,  557,  562,  476,  637,  553,  551,  640,
      561,  642,  643,  645,  646,  648,  647,  650,  670,  657,
      555,  678,  564,  563,  472,  465,  680,  651,  654,  164,
      652,  662,  659,   81,   69,  692,  847,    0,  693,  691,

      688,  689,  702,  847,    0,  702,  700,  703,  705,  708,
      710,  712,  713,  714,  715,  716,  847,  756,  762,  764,
      768,  774,  780,  786,  792,  798,  804,  810,  816,  822,
      828,  834,  840
    } ;

static yyconst short int yy_def[334] =
    {   0,
      317,    1,  318,  318,  317,  317,  317,  317,  319,  317,
      317,  317,  320,  317,  317,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  317,  322,  317,  317,  317,  319,  317,
      319,  317,  317,  323,  317,  320,  320,  320,  317,  317,
      319,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  317,  322,
      317,  317,  323,  317,  317,  317,  317,  317,  321,  321,

      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  317,
      317,  317,  317,  317,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  317,  317,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,

      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  317,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  317,  324,  325,  324,
      324,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  326,  327,  326,  326,  325,  328,  324,  325,
      325,  321,  321,  321,  321,  321,  321,  321,  327,  329,
      326,  327,  327,  317,  328,  324,  330,  321,  321,  321,
      321,  321,  317,  329,  326,  331,  317,  332,  330,  332,

      321,  321,  321,  317,  333,  331,  333,  321,  321,  321,
      321,  321,  321,  321,  321,  321,    0,  317,  317,  317,
      317,  317,  317,  317,  317,  317,  317,  317,  317,  317,
      317,  317,  317
    } ;

static yyconst short int yy_nxt[897] =
    {   0,
        6,    7,    8,    9,    6,   10,    6,    6,    6,    6,
        6,   11,   12,   13,   14,    6,   15,   16,   16,    6,
       10,   17,   18,   19,   20,   21,   16,   22,   16,   23,
       24,   16,   25,   26,   27,   16,   28,   16,   29,   30,
       31,   32,   16,   33,   16,   16,   16,   34,   10,   37,
       37,   40,   45,   43,   46,   38,   38,   44,   51,   48,
       51,   51,   51,   51,   51,   51,   48,   41,   51,   51,
       51,   51,   40,  317,  317,  317,  265,   51,   56,   57,
       51,   69,   53,  317,   51,   51,   58,   60,   41,   54,
       72,   61,   70,   59,   55,   63,   64,   62,   73,   68,

      125,   66,   71,   65,   67,   81,   76,   51,   87,   80,
       82,   83,   74,   77,   51,   42,   78,  317,   75,   79,
       92,   94,   84,   40,  317,   85,   95,   92,   45,  317,
       46,  317,   88,   95,   96,   48,  317,  317,   97,   41,
      317,  317,   48,  317,  317,  100,  317,   99,  317,   86,
      317,  317,  102,  101,  317,  317,  317,  317,  104,  317,
      317,  317,  317,  317,  106,  317,  317,  317,  317,  317,
      317,  233,   96,  103,  105,  317,  115,  113,  317,  317,
      317,  317,  317,  107,  108,  111,  109,  119,  317,  110,
      317,  112,  117,  114,  118,  116,  126,  120,  121,  122,

      123,  135,  127,  128,  124,  131,  129,  317,  133,   94,
      130,  140,  136,  139,  142,  141,  143,  317,  317,  317,
      144,  142,  317,  317,  132,  134,  317,  317,  317,  317,
      317,  317,  317,  137,  317,  317,  146,  317,  317,  317,
      317,  317,  317,  138,  317,  147,  152,  317,  149,  140,
      154,  148,  145,  156,  143,  153,  157,  158,  150,  155,
      317,  317,  317,  151,  149,  149,  166,  317,  317,  159,
      163,  317,  317,  317,  317,  160,  161,  317,  164,  317,
      162,  317,  167,  317,  317,  317,  317,  317,  317,  317,
      165,  183,  171,  317,  317,  184,  317,  317,  317,  169,

      317,  317,  170,  168,  317,  145,  175,  317,  172,  173,
      174,  179,  181,  317,  182,  187,  317,  317,  176,  180,
      186,  177,  178,  317,  185,  189,  145,  317,  317,  183,
      190,  317,  317,  191,  317,  149,  317,  317,  188,  317,
      317,  195,  192,  317,  317,  196,  317,  317,  317,  317,
      317,  193,  317,  317,  194,  317,  317,  203,  201,  202,
      317,  317,  317,  317,  317,  197,  207,  198,  213,  199,
      200,  208,  204,  212,  209,  211,  214,  205,  317,  210,
      206,  317,  317,  149,  215,  216,  317,  165,  317,  317,
      317,  317,  218,  216,  317,  317,  317,  145,  217,  317,

      317,  317,  317,  219,  145,  317,  317,  317,  317,  317,
      317,  317,  221,  224,  317,  317,  317,  317,  220,  317,
      149,  223,  149,  317,  216,  225,  317,  222,  317,  165,
      232,  145,  227,  231,  165,  229,  226,  145,  165,  317,
      317,  228,  317,  145,  317,  234,  237,  230,  317,  317,
      235,  165,  317,  236,  317,  317,  317,  317,  317,  317,
      247,  317,  240,  149,  317,  317,  317,  317,  317,  317,
      145,  317,  250,  249,  317,  238,  246,  250,  239,  264,
      242,  243,  149,  265,  241,  256,  216,  165,  244,  252,
      253,  261,  165,  260,  245,  248,  248,  257,  249,  248,

      248,  248,  250,  248,  248,  248,  248,  248,  248,  248,
      248,  248,  251,  251,  248,  248,  251,  251,  251,  251,
      251,  251,  251,  251,  251,  251,  251,  251,  251,  251,
      251,  251,  251,  251,  251,  251,  251,  251,  251,  251,
      251,  251,  248,  248,  317,  317,  317,  317,  317,  317,
      268,  269,  317,  317,  317,  270,  284,  317,  286,  280,
      281,  287,  295,  317,  282,  296,  317,  271,  270,  265,
      297,  282,  285,  298,  265,  275,  283,  259,  262,  273,
      254,  274,  255,  258,  216,  263,  263,  145,  264,  263,
      263,  263,  265,  263,  263,  263,  263,  263,  263,  263,

      263,  263,  266,  266,  263,  263,  266,  266,  266,  266,
      266,  266,  266,  266,  266,  266,  266,  266,  266,  266,
      266,  266,  266,  266,  266,  266,  266,  266,  266,  266,
      266,  266,  263,  263,  317,  317,  317,  317,  317,  268,
      269,  317,  268,  269,  270,  317,  317,  270,  317,  317,
      317,  317,  250,  317,  317,  317,  271,  317,  250,  271,
      293,  276,  278,  145,  289,  317,  304,  317,  216,  305,
      272,  288,  280,  281,  277,  292,  294,  282,  301,  290,
      280,  281,  300,  291,  290,  282,  216,  250,  302,  283,
      248,  317,  317,  303,  307,  300,  290,  283,  297,  265,

      286,  298,  263,  287,  307,  317,  317,  304,  317,  295,
      305,  317,  296,  317,  308,  317,  317,  317,  317,  317,
      184,  184,  290,  309,  317,  317,  317,  144,  144,  141,
      141,   97,   97,  314,  317,   98,   98,  311,  317,   91,
      310,   89,   51,   50,   49,   42,  315,  317,  216,  312,
      313,  216,   35,  317,  317,  316,   36,   36,   36,   36,
       36,   36,   39,   39,   39,   39,   39,   39,   47,   47,
       52,  317,  317,   52,   90,  317,   90,   90,   90,   90,
       93,  317,   93,   93,   93,   93,  248,  317,  248,  248,
      248,  248,  267,  267,  267,  267,  267,  267,  263,  317,

      263,  263,  263,  263,  279,  279,  279,  279,  279,  279,
      268,  268,  268,  268,  268,  268,  280,  280,  280,  280,
      280,  280,  299,  299,  299,  299,  299,  299,  306,  306,
      306,  306,  306,  306,  300,  300,  300,  317,  300,  300,
      307,  307,  307,  317,  307,  307,    5,  317,  317,  317,
      317,  317,  317,  317,  317,  317,  317,  317,  317,  317,
      317,  317,  317,  317,  317,  317,  317,  317,  317,  317,
      317,  317,  317,  317,  317,  317,  317,  317,  317,  317,
      317,  317,  317,  317,  317,  317,  317,  317,  317,  317,
      317,  317,  317,  317,  317,  317

    } ;

static yyconst short int yy_chk[897] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    3,
        4,    9,   13,   12,   13,    3,    4,   12,   17,   13,
       18,   19,   21,   24,   26,   20,   13,    9,   23,   22,
       25,   29,   39,   47,   78,   47,  295,   32,   18,   19,
       27,   24,   17,  294,   28,   30,   19,   20,   39,   17,
       26,   20,   25,   19,   17,   21,   21,   20,   27,   23,

       78,   22,   25,   21,   22,   30,   28,   31,   32,   29,
       30,   30,   27,   28,   33,   42,   28,   55,   27,   28,
       42,   45,   30,   51,   54,   31,   45,   42,   46,   53,
       46,   56,   33,   45,   48,   46,   48,   57,   48,   51,
       58,   60,   46,   59,   61,   54,   62,   53,   65,   31,
       63,   64,   56,   55,   66,   67,   68,   69,   58,   70,
       74,   71,   73,   72,   60,   76,   77,  290,  208,   75,
       79,  208,   48,   57,   59,   80,   69,   67,   82,   86,
       88,   83,   85,   61,   62,   65,   63,   73,   81,   64,
       84,   66,   71,   68,   72,   70,   79,   74,   75,   75,

       76,   85,   79,   80,   77,   83,   81,   87,   84,   94,
       82,   92,   86,   88,   94,   92,   95,   99,  100,  101,
       95,   94,  102,  104,   83,   84,  103,  105,  106,  107,
      109,  108,  112,   87,  111,  110,  100,  114,  115,  113,
      116,  117,  118,   87,  119,  101,  106,  122,  103,   92,
      108,  102,   99,  110,   95,  107,  111,  113,  104,  109,
      120,  121,  123,  105,  112,  117,  122,  124,  125,  114,
      119,  126,  127,  128,  130,  115,  116,  129,  120,  131,
      118,  133,  123,  134,  132,  135,  138,  137,  139,  136,
      121,  142,  127,  146,  148,  142,  147,  150,  151,  125,

      152,  154,  126,  124,  153,  128,  132,  155,  129,  130,
      131,  136,  138,  156,  139,  150,  157,  158,  133,  137,
      147,  134,  135,  159,  146,  153,  148,  160,  161,  142,
      154,  162,  163,  155,  164,  151,  166,  167,  152,  168,
      169,  159,  156,  170,  171,  160,  173,  175,  172,  176,
      178,  157,  174,  177,  158,  179,  180,  168,  166,  167,
      181,  182,  186,  188,  185,  161,  171,  162,  178,  163,
      164,  172,  168,  177,  174,  176,  179,  169,  187,  175,
      170,  189,  190,  173,  181,  185,  191,  180,  192,  193,
      194,  195,  188,  186,  196,  198,  197,  182,  187,  199,

      200,  202,  201,  189,  190,  203,  204,  205,  207,  211,
      206,  210,  194,  198,  212,  213,  217,  209,  191,  215,
      193,  197,  196,  214,  192,  198,  218,  195,  219,  211,
      207,  199,  202,  206,  210,  204,  200,  201,  209,  220,
      221,  203,  222,  213,  223,  214,  219,  205,  224,  227,
      215,  212,  228,  217,  225,  226,  229,  231,  230,  239,
      231,  232,  223,  218,  234,  244,  240,  235,  236,  243,
      220,  252,  286,  251,  285,  221,  230,  251,  222,  266,
      225,  226,  232,  266,  224,  239,  227,  234,  228,  235,
      236,  244,  252,  243,  229,  233,  233,  240,  233,  233,

      233,  233,  233,  233,  233,  233,  233,  233,  233,  233,
      233,  233,  233,  233,  233,  233,  233,  233,  233,  233,
      233,  233,  233,  233,  233,  233,  233,  233,  233,  233,
      233,  233,  233,  233,  233,  233,  233,  233,  233,  233,
      233,  233,  233,  233,  237,  238,  242,  241,  245,  246,
      249,  249,  253,  257,  255,  249,  268,  256,  269,  264,
      264,  269,  281,  271,  264,  281,  283,  249,  271,  265,
      284,  283,  268,  284,  263,  257,  264,  242,  246,  255,
      237,  256,  238,  241,  245,  247,  247,  253,  247,  247,
      247,  247,  247,  247,  247,  247,  247,  247,  247,  247,

      247,  247,  247,  247,  247,  247,  247,  247,  247,  247,
      247,  247,  247,  247,  247,  247,  247,  247,  247,  247,
      247,  247,  247,  247,  247,  247,  247,  247,  247,  247,
      247,  247,  247,  247,  254,  258,  259,  260,  261,  267,
      267,  262,  270,  270,  267,  272,  273,  270,  274,  275,
      277,  276,  250,  278,  288,  291,  267,  289,  248,  270,
      280,  258,  261,  262,  273,  292,  293,  216,  260,  293,
      254,  272,  279,  279,  259,  276,  280,  279,  288,  274,
      282,  282,  287,  275,  278,  282,  277,  287,  289,  279,
      287,  301,  302,  291,  296,  299,  292,  282,  300,  296,

      299,  300,  296,  299,  306,  303,  308,  307,  309,  306,
      307,  310,  306,  311,  302,  312,  313,  314,  315,  316,
      184,  183,  301,  303,  165,  149,  145,  144,  143,  141,
      140,   97,   96,  312,   52,   50,   49,  309,   41,   38,
      308,   34,   16,   15,   14,   11,  314,    5,  313,  310,
      311,  316,    2,    0,    0,  315,  318,  318,  318,  318,
      318,  318,  319,  319,  319,  319,  319,  319,  320,  320,
      321,    0,    0,  321,  322,    0,  322,  322,  322,  322,
      323,    0,  323,  323,  323,  323,  324,    0,  324,  324,
      324,  324,  325,  325,  325,  325,  325,  325,  326,    0,

      326,  326,  326,  326,  327,  327,  327,  327,  327,  327,
      328,  328,  328,  328,  328,  328,  329,  329,  329,  329,
      329,  329,  330,  330,  330,  330,  330,  330,  331,  331,
      331,  331,  331,  331,  332,  332,  332,    0,  332,  332,
      333,  333,  333,    0,  333,  333,  317,  317,  317,  317,
      317,  317,  317,  317,  317,  317,  317,  317,  317,  317,
      317,  317,  317,  317,  317,  317,  317,  317,  317,  317,
      317,  317,  317,  317,  317,  317,  317,  317,  317,  317,
      317,  317,  317,  317,  317,  317,  317,  317,  317,  317,
      317,  317,  317,  317,  317,  317

    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lexer.l"
#define INITIAL 0
#line 2 "lexer.l"
	#include<stdio.h>
	#include<stdlib.h>
	#include<malloc.h>
	#include<string.h>
	void insert(char*,char);
	int countentry=0;
	int comment=0;
	int bracketcount=0;
#define mcomment 1

#line 680 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		yy_current_buffer->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 22 "lexer.l"

#line 836 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 318 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 847 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 23 "lexer.l"
;
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 24 "lexer.l"
{insert(yytext,'o');}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 25 "lexer.l"
{insert(yytext,'o');}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 26 "lexer.l"
{insert(yytext,'d');}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 27 "lexer.l"
{;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 28 "lexer.l"
{printf("ERROR: Printf statement\n");}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 29 "lexer.l"
{;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 30 "lexer.l"
{printf("ERROR: Scanf statement\n");}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 31 "lexer.l"
{insert(yytext,'s');}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 32 "lexer.l"
{printf("ERROR: String Literal\n");}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 33 "lexer.l"
{insert(yytext,'k');}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 34 "lexer.l"
{insert(yytext,'k');}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 35 "lexer.l"
{insert(yytext,'k');}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 36 "lexer.l"
{BEGIN(mcomment);}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 37 "lexer.l"
{BEGIN(INITIAL);}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 38 "lexer.l"
;
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 39 "lexer.l"
;
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 40 "lexer.l"
{insert(yytext,'v');}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 41 "lexer.l"
{insert(yytext,'c');}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 42 "lexer.l"
{insert(yytext,'c');}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 43 "lexer.l"
{printf("ERROR : Bad token %s\n",yytext);}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 44 "lexer.l"
{insert(yytext,'c');}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 45 "lexer.l"
{insert(yytext,'c');}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 46 "lexer.l"
;
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 47 "lexer.l"
{insert(yytext,'p');}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 48 "lexer.l"
ECHO;
	YY_BREAK
#line 1050 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(mcomment):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 318 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 318 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 317);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	yy_current_buffer->yy_at_bol = (c == '\n');

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 48 "lexer.l"


void insert(char* yytext,char type)
{
	switch(type)
	{
		case 'v':
			fprintf(yyout,"\t%s\t\t\tIdentifier\t\t\t%d\n",yytext,countentry);
			countentry++;
			break;
		case 'c':
			fprintf(yyout,"\t%s\t\t\tConstant\t\t\t%d\n",yytext,countentry);
			countentry++;
			break;
		case 'p':
			fprintf(yyout,"\t%s\t\t\tPunctuator\t\t\t%d\n",yytext,countentry);
			countentry++;
			break;
		case 'o':
			fprintf(yyout,"\t%s\t\t\tOperator\t\t\t%d\n",yytext,countentry);
			countentry++;
			break;
		case 'k':
			fprintf(yyout,"\t%s\t\t\tKeyword\t\t\t%d\n",yytext,countentry);
			countentry++;
			break;
		case 's':
			fprintf(yyout,"\t%s\t\t\tString Literal\t\t\t%d\n",yytext,countentry);
			countentry++;
			break;
		case 'd':
			fprintf(yyout,"\t%s\t\t\tPreprocessor Statement\t\t\t%d\n",yytext,countentry);
			countentry++;
			break;
	}
}

int yywrap()
{
	return 1;
}

int main()
{
	yyin=fopen("input.c","r");
	yyout=fopen("output.txt","w");
	fprintf(yyout,"\tLexeme\t\t\tToken\t\t\tValue\n");
	yylex();
	fclose(yyout);
	fclose(yyin);
	return 0;
}